CREATE OR REPLACE FUNCTION NumberOFCards 
(MSISDN_IN NUMBER) 
RETURN NUMBER 
IS
NUM_CARDS NUMBER;
BEGIN 
SELECT COUNT(ID_CARD)
INTO NUM_CARDS
FROM CARD, ABONENT
WHERE CARD.ID_ABON=ABONENT.ID_ABON
AND ABONENT.MSISDN=MSISDN_IN;
RETURN NUM_CARDS; 
END NumberOFCards;